FROM ubuntu:16.04

#Update Ubuntu Software repository
RUN:
	apt-get update
	apt-get install -y vlc
	apt-get install -y wget
	echo "installing vlc, wget.."
	apt list --installed > installed_apps.txt
	grep . /etc/apt/sources.list /etc/apt/sources.list.d/* | grep 'http://' | sed 's/^.*\(http.*\).*$/\1/' > repo_list.txt

COPY:
	start.sh /start.sh

CMD ["./start.sh"]

EXPOSE 80 443
